// Direction artistique Kaba : outil professionnel calme, éditorial et précis, sans esthétique SaaS générique.
// Dashboard de démonstration frontend : les données affichées sont des exemples d’interface, sans connexion backend.

import { useState } from "react";
import { Bell, Building2, ChevronDown, FileText, Image as ImageIcon, LayoutDashboard, LogOut, Menu, Plus, Search, Settings, UserRound, Video, X } from "lucide-react";
import { Link } from "wouter";

const properties = [
  { image: "/manus-storage/kaba-property-ngor_3d2ef10e.jpg", title: "Une adresse ouverte sur le calme", location: "Sicap Amitié 3 · Dakar", status: "Publié", views: "248" },
  { image: "/manus-storage/kaba-property-almadies_64bab9ed.jpg", title: "Lumière douce, volumes justes", location: "Almadies · Dakar", status: "En attente", views: "94" },
  { image: "/manus-storage/kaba-land-dakar_98970f8e.jpg", title: "Un horizon à construire", location: "Lac Rose · Sénégal", status: "Brouillon", views: "—" },
];

const menu = [
  { label: "Vue d’ensemble", icon: LayoutDashboard },
  { label: "Mes biens", icon: Building2 },
  { label: "Médias", icon: ImageIcon },
  { label: "Demandes reçues", icon: FileText },
  { label: "Mon profil", icon: UserRound },
];

export default function Dashboard() {
  const [active, setActive] = useState("Vue d’ensemble");
  const [menuOpen, setMenuOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);

  return <main className="dashboard-shell"><aside className={menuOpen ? "dashboard-sidebar is-open" : "dashboard-sidebar"}><div className="dashboard-brand"><span className="dashboard-mark">K</span><span>Kaba</span><small>ESPACE PRO</small></div><nav className="dashboard-nav" aria-label="Navigation du dashboard">{menu.map(({ label, icon: Icon }) => <button className={active === label ? "is-active" : ""} key={label} onClick={() => { setActive(label); setMenuOpen(false); }}><Icon size={17} />{label}{label === "Demandes reçues" && <b>3</b>}</button>)}</nav><div className="dashboard-sidebar-bottom"><button><Settings size={16} /> Paramètres</button><Link href="/"><LogOut size={16} /> Quitter l’espace</Link></div></aside><section className="dashboard-main"><header className="dashboard-header"><button className="dashboard-menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Ouvrir le menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><div><p className="dashboard-breadcrumb">ESPACE PROFESSIONNEL <span>/</span> {active.toUpperCase()}</p><h1>{active}</h1></div><div className="dashboard-header-actions"><button className="dashboard-notification" aria-label="Notifications"><Bell size={18} /><i /></button><div className="dashboard-profile-wrap"><button className="dashboard-profile" onClick={() => setProfileOpen(!profileOpen)}><span className="dashboard-avatar">CK</span><span><strong>Cheikh Kanté</strong><small>Agent immobilier</small></span><ChevronDown size={15} /></button>{profileOpen && <div className="dashboard-profile-menu"><Link href="/register">Modifier le profil</Link><Link href="/">Se déconnecter</Link></div>}</div></div></header>{active === "Vue d’ensemble" && <Overview onAdd={() => setActive("Mes biens")} />}{active === "Mes biens" && <Properties onAdd={() => undefined} />}{active === "Médias" && <MediaLibrary />}{active === "Demandes reçues" && <Requests />}{active === "Mon profil" && <Profile />}</section></main>;
}

function Overview({ onAdd }: { onAdd: () => void }) { return <div className="dashboard-content"><div className="dashboard-welcome"><div><p className="eyebrow"><span>01</span> Bonjour Cheikh</p><h2>Votre activité,<br /><em>en un regard.</em></h2></div><button className="dashboard-primary" onClick={onAdd}><Plus size={16} /> Ajouter un bien</button></div><div className="dashboard-stats"><div><span>Biens publiés</span><strong>04</strong><small>+1 ce mois-ci</small></div><div><span>Vues ce mois</span><strong>1 248</strong><small>+18% depuis avril</small></div><div><span>Demandes reçues</span><strong>12</strong><small>3 nouvelles demandes</small></div><div><span>Taux de réponse</span><strong>86%</strong><small>Très bon niveau</small></div></div><div className="dashboard-section-head"><div><p className="eyebrow"><span>02</span> Vos adresses</p><h3>Biens récemment<br /><em>regardés.</em></h3></div><button className="dashboard-text-button" onClick={onAdd}>Voir tous les biens →</button></div><div className="dashboard-property-grid">{properties.map((property) => <article className="dashboard-property-card" key={property.title}><div className="dashboard-property-image"><img src={property.image} alt="" /><span className={`status status-${property.status.replace("é", "e").toLowerCase()}`}>{property.status}</span></div><div className="dashboard-property-copy"><h4>{property.title}</h4><p>{property.location}</p><span>{property.views} vues</span></div></article>)}</div></div>; }

function Properties({ onAdd }: { onAdd: () => void }) { return <div className="dashboard-content"><div className="dashboard-toolbar"><div className="dashboard-search"><Search size={16} /><input placeholder="Rechercher dans vos biens" /></div><button className="dashboard-primary" onClick={onAdd}><Plus size={16} /> Ajouter un bien</button></div><div className="dashboard-table"><div className="dashboard-table-head"><span>Bien</span><span>Statut</span><span>Vues</span><span>Dernière modification</span><span /></div>{properties.map((property) => <div className="dashboard-table-row" key={property.title}><div className="table-property"><img src={property.image} alt="" /><span><strong>{property.title}</strong><small>{property.location}</small></span></div><span className={`status status-${property.status.replace("é", "e").toLowerCase()}`}>{property.status}</span><span>{property.views}</span><span>Il y a 2 jours</span><button aria-label="Ouvrir les options">···</button></div>)}</div></div>; }

function MediaLibrary() { return <div className="dashboard-content"><div className="dashboard-section-head"><div><p className="eyebrow"><span>02</span> Bibliothèque</p><h3>Vos images,<br /><em>vos films.</em></h3></div><button className="dashboard-primary"><Plus size={16} /> Importer un média</button></div><div className="dashboard-media-grid">{properties.flatMap((property, index) => [property.image, index === 0 ? "/manus-storage/kaba-hero-dakar_28cefd79.jpg" : property.image]).map((image, index) => <div className="dashboard-media-card" key={`${image}-${index}`}><img src={image} alt="Média de bien immobilier" />{index === 2 && <span><Video size={13} /> Film</span>}</div>)}</div></div>; }

function Requests() { return <div className="dashboard-content"><div className="dashboard-section-head"><div><p className="eyebrow"><span>03</span> Relation</p><h3>Les personnes qui<br /><em>regardent vos biens.</em></h3></div></div><div className="dashboard-requests">{["Aminata Ndiaye", "Moussa Diop", "Fatou Sarr"].map((name, index) => <div className="dashboard-request" key={name}><span className="request-avatar">{name.split(" ").map((part) => part[0]).join("")}</span><div><strong>{name}</strong><p>Intéressé(e) par « {properties[index].title} »</p></div><small>{index === 0 ? "Aujourd’hui" : `Il y a ${index + 1} jours`}</small><button>Répondre →</button></div>)}</div></div>; }

function Profile() { return <div className="dashboard-content"><div className="profile-card"><div className="profile-card-top"><span className="dashboard-avatar large">CK</span><div><p className="eyebrow"><span>04</span> Profil professionnel</p><h3>Cheikh Kanté</h3><p>Agent immobilier · Dakar</p></div><span className="verified"><span>✓</span> Profil vérifié</span></div><div className="profile-fields"><label>Nom complet<input value="Cheikh Kanté" readOnly /></label><label>Email professionnel<input value="cheikhkanteye.contact@gmail.com" readOnly /></label><label>Téléphone<input value="+221 77 818 78 64" readOnly /></label><label>Zone d’activité<input value="Almadies · Dakar" readOnly /></label></div><button className="dashboard-primary">Modifier mes informations <Settings size={15} /></button></div></div>; }
